export const CANVAS_WIDTH_METERS = 10;
export const DESIRED_LETTER_WIDTH_METERS = 1;
export const LINEAR_SPEED_THRESHOLD = 0.1;
export const ANGULAR_SPEED_THRESHOLD = 0.1;
export const MIN_SECONDS_STABLE = 3;